# Generated by Django 3.2.5 on 2021-10-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.IntegerField(max_length=20)),
                ('address', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
